name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: op://Publish/KNotion Publish/ORG_GRADLE_PROJECT_signingInMemoryKeyId
          ORG_GRADLE_PROJECT_signingInMemoryKey: op://Publish/KNotion Publish/ORG_GRADLE_PROJECT_signingInMemoryKey
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: op://Publish/KNotion Publish/ORG_GRADLE_PROJECT_signingInMemoryKeyPassword
          ORG_GRADLE_PROJECT_mavenCentralUsername: op://Publish/KNotion Publish/ORG_GRADLE_PROJECT_mavenCentralUsername
          ORG_GRADLE_PROJECT_mavenCentralPassword: op://Publish/KNotion Publish/ORG_GRADLE_PROJECT_mavenCentralPassword

      - name: Publish to Maven Central
        run: ./gradlew :library:publishAllPublicationsToMavenCentralRepository